### ISSUE TITLE
Significant gender imbalance

### ISSUE THREAD

**Issue by MartinBurnsSV** [RandomAPI/Randomuser.me-Source#58]
Small dataset, I know, but only 1/12 returned results were women.

We can do better than this.

**Comment by keitharm** [comment]
How large is your sample size to come to the conclusion that 11/12 of the results are male and 1/12 are female?

Regardless of the size of our dataset, gender is determined by a [random](https://www.youtube.com/watch?v=9rIy0xY99a0) number between 0 and 1. 1 = male and 0 = female. The server uses the Mersenne Twister PRNG for generating all of the random values as well as rng-tools to increase the available entropy.

Sometimes you get 11 heads in a row and sometimes you get 50/50 heads and tails.
